language: python
python: 3.6
before_install:
  - sudo apt-get install octave
install:
  - pip install -r requirements.txt
  - pip install oct2py codecov pytest pytest-cov
script:
  - pytest --cov=./
after_success:
  - codecov